# secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: messaging-secret
  namespace: default 
type: Opaque
stringData:
  JWT_SECRET: "cN7iET34LHJDSms4If3948"
  DATABASE_URL: "postgresql://postgres:postgres@postgres-service:5432/messagingApp?sslmode=disable"

