# service.yml
apiVersion: v1
kind: Service
metadata:
  name: messaging-service
  namespace: default
spec:
  selector:
    app: messaging-server
  ports:
    - port: 80
      targetPort: 4000
  type: ClusterIP
